package fr.tolc.jahia.intellij.plugin.cnd;

import com.intellij.testFramework.ParsingTestCase;

/**
 * Golden parsing tests over the real Jahia definition files.
 *
 * <p>Each fixture in {@code testResources/parsing} is parsed and its PSI tree compared against a
 * committed {@code .txt} dump. Nothing here asserts that the grammar is <em>right</em> -- it
 * asserts that it does not change unnoticed, which is what has been missing: the changelogs for
 * 1.3, 2.1.0, 2.1.1 and 2.2.0 are all grammar fixes, and {@code Cnd.bnf} and {@code Cnd.flex} could
 * not be touched with any confidence.
 *
 * <p>These baselines are also the prerequisite for ever generating the parser at build time: the
 * {@code gen/} tree and {@code CndLexer.java} are committed and regenerated by hand today, and
 * without a baseline there is no way to prove a regenerated parser behaves identically.
 *
 * <p>To re-record a baseline after an intentional grammar change: delete the {@code .txt} beside
 * the fixture and run the test once. It writes the new dump and fails; read the diff before
 * committing it.
 *
 * @see CndParsingErrorsTest for the assertion that no fixture parses with errors
 */
public class CndParsingTest extends ParsingTestCase {

    public CndParsingTest() {
        super("parsing", "cnd", new CndParserDefinition());
    }

    @Override
    protected String getTestDataPath() {
        return "testResources";
    }

    @Override
    protected boolean skipSpaces() {
        // Whitespace is part of what the lexer decides; skipping it would hide state-machine
        // regressions in Cnd.flex, which is where this grammar has historically broken.
        return false;
    }

    @Override
    protected boolean includeRanges() {
        return true;
    }

    public void testSystemNodetypes() {
        doTest(true);
    }

    public void testJahiaNodetypes() {
        doTest(true);
    }

    public void testJahiaNodetypes7120() {
        doTest(true);
    }

    public void testStandardTypes() {
        doTest(true);
    }

    public void testExtensionNodetypes() {
        doTest(true);
    }

    public void testInternalNodetypes() {
        doTest(true);
    }

    public void testDef2() {
        doTest(true);
    }

    public void testJahiaTests() {
        doTest(true);
    }

    public void testTestFile() {
        doTest(true);
    }

    public void testV7121SystemNodetypes() {
        doTest(true);
    }

    public void testV7121JahiacoreNodetypes() {
        doTest(true);
    }

    public void testV7121FilesNodetypes() {
        doTest(true);
    }

    public void testV7121JahiacontentNodetypes() {
        doTest(true);
    }

    public void testV7121StandardTypes() {
        doTest(true);
    }

    public void testV7121ExtensionNodetypes() {
        doTest(true);
    }

    public void testV7121PreferencesNodetypes() {
        doTest(true);
    }
}
